In [1]:
import pandas as pd

In [7]:
df = pd.read_json('/Users/eric/Downloads/bso-clinical-trials-2022-01-06_20220107.jsonl.gz', lines=True)

In [8]:
df.columns

Index(['all_sources', 'has_results', 'NCTId', 'other_ids', 'title', 'acronym',
       'summary', 'study_start_date', 'study_start_date_type', 'status',
       'study_completion_date', 'study_completion_date_type',
       'study_first_submit_date', 'study_first_submit_qc_date', 'study_type',
       'design_allocation', 'primary_purpose', 'enrollment_count',
       'enrollment_type', 'has_publications_result',
       'has_results_or_publications', 'lead_sponsor', 'location_country',
       'location_facility', 'intervention_type', 'snapshot_date',
       'study_start_year', 'study_completion_year', 'delay_submission_start',
       'submission_temporality', 'delay_start_completion', 'lead_sponsor_type',
       'french_location_only', 'references', 'status_simplified',
       'has_publication_oa', 'publication_access', 'time_perspective',
       'ipd_sharing', 'eudraCT', 'publications_result',
       'first_publication_date', 'first_results_or_publication_date',
       'delay_first_results_completion', 'results_first_submit_date',
       'results_first_submit_qc_date', 'WHO', 'ISRCTN'],
      dtype='object')

In [17]:
df[['study_type', 'design_allocation']].dropna()

           study_type design_allocation
0      Interventional               N/A
9      Interventional        Randomized
11     Interventional    Non-Randomized
12     Interventional        Randomized
13     Interventional        Randomized
...               ...               ...
32855  Interventional        Randomized
32856  Interventional               N/A
32976  Interventional               N/A
33253  Interventional        Randomized
33286  Interventional    Non-Randomized

[20976 rows x 2 columns]

In [23]:
df.eudraCT.value_counts().head(30)

2016-004754-15    3
2014-002597-37    3
2013-004384-31    2
2015-002548-15    2
2017-003345-15    2
2013-005486-39    2
2010-022080-34    2
2013-000307-17    2
2011-001729-25    2
2010-023137-34    2
2007-003013-14    2
2012-001963-66    2
2019-000814-13    2
2019-002315-26    2
2015-005008-27    2
2006-004495-13    2
2014-003929-17    2
2020-001246-18    2
2016-002129-12    2
2011-003184-29    2
2007-002627-32    2
2010-019224-31    2
2020-005759-18    2
2016-002122-36    2
2007-003233-16    1
2014-002560-33    1
2020-004805-30    1
2009-017029-20    1
2007-007941-10    1
2007-003905-28    1
Name: eudraCT, dtype: int64

In [24]:
df[df.eudraCT=="2015-005008-27"]

,ISRCTN,NCTId,WHO,acronym,all_sources,delay_first_results_completion,delay_start_completion,delay_submission_start,design_allocation,enrollment_count,...,study_completion_year,study_first_submit_date,study_first_submit_qc_date,study_start_date,study_start_date_type,study_start_year,study_type,submission_temporality,time_perspective,title
24994,NaN,NCT04880434,NaN,ZUMA-2,clinical_trials;euctr,NaN,6447.0,3.0,NaN,90.0,...,2038.0,2021-04-30T00:00:00,2021-05-05T00:00:00,2021-04-27T00:00:00,Actual,2021.0,Interventional,during_study,NaN,A Phase 2 Multicenter Study Evaluating the Eff...
27884,NaN,NCT02601313,NaN,ZUMA-2,clinical_trials;euctr,-6776.0,8382.0,-3.0,NaN,105.0,...,2038.0,2015-11-06T00:00:00,2015-11-06T00:00:00,2015-11-09T00:00:00,Actual,2015.0,Interventional,before_start,NaN,A Phase 2 Multicenter Study Evaluating the Eff...

In [26]:
dx.NCTId.to_clipboard(index=False)